#include<iostream.h>
#include<conio.h>

int main()
{ int x,y,z;
clrscr();
 cout<<"now its time for fun.....;-0"<<"\n"<<"lets get start....8-0"<<"\n"<<"enter any number......@-9";
  cin>>x>>y;
  cout<<"lets see whats is in your destiny"<<"\n";
  z=x+y;
  cout<<z<<"\n";
  cout<<"very good"<<"\n"<<"again"<<"\n";
  cout<<"eneter any two number"<<"\n";
  cin>>x>>y;
  z=x*y;
  cout<<z<<"\n";

  cout<<"now its over";
  getch();



}
